### PR TITLE
Add keyboard close-tabs support (& improve build process)

### PR DESCRIPTION
**Pull request by i404788**

### CODE REVIEW

**Review by ericpromislow — CHANGES_REQUESTED** [review]
Thanks for the contribution.

It didn't work on Firefox/macOS, but this does: 

```
@ -629,6 +629,8 @@ function processArrowKey_aux(event) {

     var selectedItems = getSelectedItemsJQ();
     var keyName = event.key;
+    var lcKeyName = keyName.toLowerCase();
+    console.log(`arrow-key: keyName: ${ keyName }, mask: ${ mask }`);
     if (keyName == "Enter") {
         if (mask != 0) {
             console.log("tabhunter: Enter can't be modified with shift, etc.");
@@ -642,7 +644,7 @@ function processArrowKey_aux(event) {
         event.stopPropagation();
         event.preventDefault();
         return;
-    } else if (keyName == "Delete") {
+    } else if (mask === 0 && (lcKeyName == "delete" || lcKeyName == "backspace")) {
         doCloseTabsButton();
         event.stopPropagation();
         event.preventDefault();
```

I prefer to match ignoring case to pick up more combinations of `platform x browser`, and also verify there's no modifier key, in case in the future it makes sense to assign some other function to a combination backspace/delete + `X` key.

Otherwise looks great.

**Comment by i404788** [comment]
Didn't realize the keycodes are not standardized. I tested with Firefox/Linux, but I suppose `Delete` is also not as commonly used on OSX due to the fn+backspace.
I've applied your patch.

**Comment by ericpromislow** [comment]
I just noticed that `console.log` stmt -- slipped past me. oh well... 3.5.1 on its way then. 3.5.0 is live on the firefox addons site, chrome takes longer to approve

**Comment by ericpromislow** [comment]
... and it turns out that this removes delete functionality in the pattern field, and probably any other input-text field as well (and there are plenty, most of them hidden in the drop-down panel and the search-tab panel.

If you can convince me that there is a way to distinguish tab-close backspace events from all other backspace events, I'll accept the change. But in the meantime it's too destructive.

Sorry, I was really hoping for a code-based PR, and didn't test this enough.

**Comment by i404788** [comment]
Hmm yeah you're right it would block textfields, would need to check for focus & selected items, I'll retry with a better PR later

**Pull request merged**
